---
title: "DATAAA FINAL LIMPIA - TRABAJO MIGRACION"
author: "Arianaa Baldeon"
date: "2024-11-09"
output: html_document
---
DATA1 - MIGRACION NETA - DATA_CLEAN4

```{r}
library(rio)
library(readr)
library(tidyr)
data4 = read_excel("MIGRACION_NETA.Xlsx")
```
```{r}
str(data4)
```
```{r}
library(tidyr)

# Pivotar los datos para poner los años en una columna
data_clean4 <- data4 %>%
  pivot_longer(
    cols = starts_with("MIGRACIONNETA") | starts_with("2019"),  # Selecciona las columnas con los datos de Estimate y Rank
    names_to = c(".value", "year"),  # Divide el nombre de la columna en "Year" y el valor de la columna
    names_pattern = "(.*)_(.*)"  # El patrón extrae "Estimate" o "Rank" y el año (2019, 2020, etc.)
  )

# Ver los primeros registros después de pivotar
head(data_clean4)
```
```{r}
colSums(is.na(data_clean4))
```

DATA2 - CRISIS POLITICA - DF_LONG
```{r setup, include=FALSE}
library(rio)
library(readr)
library(tidyr)
library(readxl)

# Cargar el archivo CSV (ajusta la ruta según corresponda)
data3 = read_excel("CRISIS_POLITICA.Xlsx", sheet = "Political StabilityNoViolence", col_names = FALSE)  # Asegúrate de que no se asigne un nombre a las columnas

colnames(data3)

data_clean3 <- data3

```
```{r}
head(data_clean3)

```
```{r}
# Si no tienes los nombres de las columnas
colnames(data_clean3) <- c("COUNTRY_NAME", "COUNTRY_CODE", "Estimate_2019", "Rank_2019", "Estimate_2020", "Rank_2020",
                  "Estimate_2021", "Rank_2021", "Estimate_2022", "Rank_2022")

```
```{r}
library(dplyr)

data_clean3 <- data_clean3 %>%
  mutate(across(everything(), ~na_if(., "#N/A")))  # Reemplazar #N/A por NA en todas las columnas

data_clean3 <- data_clean3[-(1:2), ]
head(data_clean3)

```
```{r}
library(tidyr)

# Pivotar los datos para poner los años en una columna
df_long <- data_clean3 %>%
  pivot_longer(
    cols = starts_with("Estimate") | starts_with("Rank"),  # Selecciona las columnas con los datos de Estimate y Rank
    names_to = c(".value", "year"),  # Divide el nombre de la columna en "Year" y el valor de la columna
    names_pattern = "(.*)_(.*)"  # El patrón extrae "Estimate" o "Rank" y el año (2019, 2020, etc.)
  )

# Ver los primeros registros después de pivotar
head(df_long)

```
```{r}
colSums(is.na(df_long))
# Eliminar filas con cualquier NA
df_long <- na.omit(df_long)


```
```{r}
colSums(is.na(df_long))
str(df_long)
# Convertir una columna específica de carácter a numérico
df_long$Estimate <- as.numeric(df_long$Estimate)
df_long$Rank = as.numeric(df_long$Rank)
```
```{r}
str(df_long)
```
```{r}
df_long <- df_long %>%
  mutate(across(where(is.numeric), round, 4))
```

DATA3 - CONFLICTOS ARMADOS - DATADESPLAZADOS_CONFLICTOS_ARMADOS_AMEU
CONFLICTOS ARMADOS AMERICA
```{r}
library(rio)
library(readr)
library(tidyr)

# Cargar el archivo CSV (ajusta la ruta según corresponda)
data1<- read_csv("CONFLICTOS_ARMADOS_AMERICA.csv", col_names = FALSE)  # Asegúrate de que no se asigne un nombre a las columnas

data_clean1 <- data1 %>%
  separate(X1, into = c("year", "COUNTRY_NAME", "COUNTRY_CODE", "Country_of_asylum", "Country_of_asylum_ISO", "TotalDESPLAZADOS_CA"), sep = ",")

colnames(data_clean1)
```
```{r}
library(dplyr)
# Eliminar columnas innecesarias (por ejemplo, las que contienen guiones)
data_clean1 <- data_clean1 %>%
  select(year, COUNTRY_NAME, COUNTRY_CODE, TotalDESPLAZADOS_CA) %>%
  filter(TotalDESPLAZADOS_CA != "-")  # Eliminar filas con guiones en la columna Total

```
```{r}
# Convertir "Year" y "Total" a numérico
data_clean1$year <- as.numeric(data_clean1$year)
data_clean1$TotalDESPLAZADOS_CA <- as.numeric(data_clean1$TotalDESPLAZADOS_CA)

# Verificar los primeros registros
head(data_clean1)

```
```{r}

data_clean1 <- data_clean1[-(1:3), ]
head(data_clean1)
```

CONFLICTOS ARMADOS EUROPA
```{r}
library(rio)
library(readr)
library(tidyr)

# Cargar el archivo CSV (ajusta la ruta según corresponda)
data2 <- read_csv("CONFLICTOS_ARMADOS_EUROPA.csv", col_names = FALSE)  # Asegúrate de que no se asigne un nombre a las columnas

data_clean2 <- data2 %>%
  separate(X1, into = c("year", "COUNTRY_NAME", "COUNTRY_CODE", "Country_of_asylum", "Country_of_asylum_ISO", "TotalDESPLAZADOS_CA"), sep = ",")

colnames(data_clean2)
```
```{r}
# Eliminar columnas innecesarias (por ejemplo, las que contienen guiones)
data_clean2 <- data_clean2 %>%
  select(year, COUNTRY_NAME, COUNTRY_CODE, TotalDESPLAZADOS_CA) %>%
  filter(TotalDESPLAZADOS_CA != "-")  # Eliminar filas con guiones en la columna Total

```
```{r}
# Convertir "Year" y "Total" a numérico
data_clean2$year <- as.numeric(data_clean2$year)
data_clean2$TotalDESPLAZADOS_CA <- as.numeric(data_clean2$TotalDESPLAZADOS_CA)

# Verificar los primeros registros
head(data_clean2)
```
```{r}
data_clean2 <- data_clean2[-(1), ]
head(data_clean2)
```
### DATA COMBINADA DE CONFLICTOS ARMADOS - DATADESPLAZADOS_CONFLICTOS_ARMADOS_AMEU
```{r}
# Combinar las filas de df2 con df1
DATADESPLAZADOS_CONFLICTOS_ARMADOS_AMyEU <- bind_rows(data_clean1, data_clean2)

```
DATA4 - INDICE DE GINI - DATA 5
```{r}
library(rio)
data5= read_excel("INDICE_GINI.Xlsx")
str(data5)
```
```{r}
# Reemplazar ".." por "0" en todas las columnas de tipo carácter
data5 <- data5 %>%
  mutate(across(where(is.character), ~ gsub("\\.\\.", "0", .)))
str(data5)

```
```{r}
data5$INDICEGINI_2019 = as.numeric(data5$INDICEGINI_2019)
data5$INDICEGINI_2020 = as.numeric(data5$INDICEGINI_2020)
data5$INDICEGINI_2021 = as.numeric(data5$INDICEGINI_2021)
data5$INDICEGINI_2022 = as.numeric(data5$INDICEGINI_2022)
data5$INDICEGINI_2023 = as.numeric(data5$INDICEGINI_2023)

data5 <- data5 %>%
  mutate(across(where(is.numeric), round, 4))
```
```{r}
library(tidyr)

# Pivotar los datos para poner los años en una columna
data5 <- data5 %>%
  pivot_longer(
    cols = starts_with("INDICEGINI") | starts_with("2019"),  # Selecciona las columnas con los datos de Estimate y Rank
    names_to = c(".value", "year"),  # Divide el nombre de la columna en "Year" y el valor de la columna
    names_pattern = "(.*)_(.*)"  # El patrón extrae "Estimate" o "Rank" y el año (2019, 2020, etc.)
  )

# Ver los primeros registros después de pivotar
head(data5)
```
```{r}
colSums(is.na(data5))
```

UNIR DATAS?
```{r}
# Unir df1 y df2 por la columna 'Country/Territory'
DATA_MIGRACION <- merge(data5, data_clean4, by = c("COUNTRY_CODE", "year","COUNTRY_NAME"), by.y = c("COUNTRY_CODE", "year","COUNTRY_NAME"), all = TRUE)
DATA_MIGRACION1 = merge(DATA_MIGRACION,df_long, by = c("COUNTRY_CODE", "year","COUNTRY_NAME"), by.y = c("COUNTRY_CODE", "year","COUNTRY_NAME"), all = TRUE)
DATA_MIGRACION_FINAL = merge(DATA_MIGRACION1,DATADESPLAZADOS_CONFLICTOS_ARMADOS_AMyEU, by = c("COUNTRY_CODE", "year","COUNTRY_NAME"), by.y = c("COUNTRY_CODE", "year","COUNTRY_NAME"), all = TRUE)
```

```{r}
# Cargar el paquete writexl
#install.packages("writexl")
library(writexl)

# Guardar en un archivo Excel
#write_xlsx(DATA_MIGRACION_FINAL, "DATA_MIGRACION_FINAL.xlsx")
write_xlsx(DATA_MIGRACION_FINAL, "C:/Users/arian/OneDrive/Documentos/DATA_MIGRACION_FINAL.xlsx")



```




















